services:
  frontend:
    image: ceocok/shadowssh-frontend:latest
    pull_policy: always
    container_name: shadowssh-frontend
    restart: unless-stopped
    ports:
      - "18111:80"
    depends_on:
      - backend
    networks:
      - shadowssh-network

  backend:
    image: ceocok/shadowssh-backend:latest
    pull_policy: always
    container_name: shadowssh-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
    volumes:
      - ./data:/app/data
    networks:
      - shadowssh-network

networks:
  shadowssh-network:
    driver: bridge
    name: shadowssh-network
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd01::/80    
          gateway: fd01::1    
